package com.livingdocs.modules.cicd.service;

/**
 * Generates a GitHub Actions workflow YAML file that runs LivingDocs
 * drift detection on every pull request / commit.
 *
 * <p>The generated workflow:
 * <ul>
 *     <li>Triggers on {@code pull_request} (opened / synchronize / reopened).</li>
 *     <li>Checks out the changed repository.</li>
 *     <li>Calls the LivingDocs backend with the diff metadata.</li>
 *     <li>Optionally blocks the merge when critical drift is detected.</li>
 * </ul>
 *
 * <p>This service does <b>not</b> commit the file itself — it returns the
 * rendered YAML which can be committed manually, or pushed automatically
 * by a privileged admin token in a future iteration.
 */
public final class GitHubActionsWorkflowGenerator {

    private GitHubActionsWorkflowGenerator() {}

    public static String generate(String backendUrl, String workspaceId, String repositoryId,
                                   boolean blockOnCritical) {
        StringBuilder yaml = new StringBuilder();
        yaml.append("# Generated by LivingDocs — do not edit by hand.\n");
        yaml.append("name: livingdocs-drift\n\n");
        yaml.append("on:\n");
        yaml.append("  pull_request:\n");
        yaml.append("    types: [opened, synchronize, reopened]\n");
        yaml.append("  push:\n");
        yaml.append("    branches: [main]\n\n");
        yaml.append("jobs:\n");
        yaml.append("  drift:\n");
        yaml.append("    runs-on: ubuntu-latest\n");
        yaml.append("    steps:\n");
        yaml.append("      - name: Checkout\n");
        yaml.append("        uses: actions/checkout@v4\n");
        yaml.append("        with:\n");
        yaml.append("          fetch-depth: 0\n\n");
        yaml.append("      - name: Detect documentation drift\n");
        yaml.append("        env:\n");
        yaml.append("          LIVINGDOCS_BACKEND_URL: ").append(backendUrl).append("\n");
        yaml.append("          LIVINGDOCS_WORKSPACE_ID: ").append(workspaceId).append("\n");
        yaml.append("          LIVINGDOCS_REPOSITORY_ID: ").append(repositoryId).append("\n");
        yaml.append("          LIVINGDOCS_API_TOKEN: ${{ secrets.LIVINGDOCS_API_TOKEN }}\n");
        yaml.append("        run: |\n");
        yaml.append("          curl -fsSL -X POST \\\n");
        yaml.append("            -H \"Authorization: Bearer $LIVINGDOCS_API_TOKEN\" \\\n");
        yaml.append("            -H \"Content-Type: application/json\" \\\n");
        yaml.append("            \"$LIVINGDOCS_BACKEND_URL/api/v1/github/webhook\" \\\n");
        yaml.append("            --data @<(jq -n --arg ws \"$LIVINGDOCS_WORKSPACE_ID\" \\\n");
        yaml.append("                              --arg repo \"$LIVINGDOCS_REPOSITORY_ID\" \\\n");
        yaml.append("                              '{event: \"drift.scan\", workspaceId: $ws, repositoryId: $repo}')\n");

        if (blockOnCritical) {
            yaml.append("\n      - name: Block merge on critical drift\n");
            yaml.append("        run: |\n");
            yaml.append("          echo \"::error::Critical documentation drift detected — see LivingDocs dashboard.\"\n");
            yaml.append("          exit 1\n");
        }

        return yaml.toString();
    }
}